const db = require("./db");

// Database DDL (for testing)
const DDL = `

  CREATE TABLE users (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name TEXT,
      email TEXT
  );

  CREATE TABLE questions (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      question TEXT
  );

  CREATE TABLE answers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    answer TEXT,
    user_id INTEGER REFERENCES users,
    question_id INTEGER REFERENCES questions
  );`
;

async function seedData() {
  try {
    await db.query(DDL);
    
    const questions1 = await db.query(`
    INSERT INTO questions(id, question) VALUES
    (1, 'Who survives the Battle of Winterfell?'),
    (2, 'Who kills the Night King?'),
    (3, 'What does the Night King actually want?'),
    (4, 'What is Bran?'),
    (5, 'What happened to the Dothraki?'),
    (6, 'Where is Melisandre?');

    INSERT INTO users(id, name, email) VALUES
    (123456, 'Jon Snow','kingindanorf@winterfell.com'),
    (123457, 'Arya Stark','noone@nowhere.com'),
    (123458, 'Podric','podric@lol.com');

    INSERT INTO answers(id, answer,user_id,question_id) VALUES
    (3456789,'dakingindanorf',123456,1),
    (3456790, 'dakingindanorf',123456,2),
    (3456791, 'dakingindanorf',123456,3),
    (3456792, 'dakingindanorf',123456,4),
    (3456793, 'dakingindanorf',123456,5),
    (3456794, 'dakingindanorf',123456,6)`
    );
  } catch (err) {
    console.log("Something went wrong!");
    console.log(err);
    process.exit(1);
  }
}

seedData().then(() => {
  console.log("Successful seed!");
  process.exit();
});
